/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quad_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_c3 CASADI_PREFIX(c3)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[3] = {0., 0., 9.8100000000000005e+00};
static const casadi_real casadi_c1[4] = {-1.7394826817189071e-01, -1.7394826817189071e-01, 1.7394826817189071e-01, 1.7394826817189071e-01};
static const casadi_real casadi_c2[4] = {1.7394826817189071e-01, -1.7394826817189071e-01, -1.7394826817189071e-01, 1.7394826817189071e-01};
static const casadi_real casadi_c3[4] = {-1.6000000000000000e-02, 1.6000000000000000e-02, -1.6000000000000000e-02, 1.6000000000000000e-02};

/* quad_expl_ode_fun:(i0[13],i1[4],i2[17])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, w1, *w2=w+8, w3, w4, w5, w6, w7, w8, w9, *w10=w+19, *w11=w+23, *w12=w+27, *w13=w+31, *w14=w+35, *w15=w+51, w16, w17, w18, w19, w20, w21, w22, w23, w24, w25, *w26=w+77, *w27=w+80, *w28=w+83, *w29=w+86, *w30=w+95;
  /* #0: @0 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+7 : 0, 3, w0);
  /* #1: output[0][0] = @0 */
  casadi_copy(w0, 3, res[0]);
  /* #2: @1 = 0.5 */
  w1 = 5.0000000000000000e-01;
  /* #3: @2 = zeros(4x1) */
  casadi_clear(w2, 4);
  /* #4: @3 = 0 */
  w3 = 0.;
  /* #5: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w0);
  /* #6: @4 = @0[0] */
  for (rr=(&w4), ss=w0+0; ss!=w0+1; ss+=1) *rr++ = *ss;
  /* #7: @5 = (-@4) */
  w5 = (- w4 );
  /* #8: @6 = @0[1] */
  for (rr=(&w6), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #9: @7 = (-@6) */
  w7 = (- w6 );
  /* #10: @8 = @0[2] */
  for (rr=(&w8), ss=w0+2; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #11: @9 = (-@8) */
  w9 = (- w8 );
  /* #12: @10 = horzcat(@3, @5, @7, @9) */
  rr=w10;
  *rr++ = w3;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w9;
  /* #13: @10 = @10' */
  /* #14: @11 = horzcat(@4, @3, @8, @7) */
  rr=w11;
  *rr++ = w4;
  *rr++ = w3;
  *rr++ = w8;
  *rr++ = w7;
  /* #15: @11 = @11' */
  /* #16: @12 = horzcat(@6, @9, @3, @4) */
  rr=w12;
  *rr++ = w6;
  *rr++ = w9;
  *rr++ = w3;
  *rr++ = w4;
  /* #17: @12 = @12' */
  /* #18: @13 = horzcat(@8, @6, @5, @3) */
  rr=w13;
  *rr++ = w8;
  *rr++ = w6;
  *rr++ = w5;
  *rr++ = w3;
  /* #19: @13 = @13' */
  /* #20: @14 = horzcat(@10, @11, @12, @13) */
  rr=w14;
  for (i=0, cs=w10; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #21: @15 = @14' */
  for (i=0, rr=w15, cs=w14; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #22: @10 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w10);
  /* #23: @2 = mac(@15,@10,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w15+j, tt=w10+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #24: @2 = (@1*@2) */
  for (i=0, rr=w2, cs=w2; i<4; ++i) (*rr++)  = (w1*(*cs++));
  /* #25: output[0][1] = @2 */
  if (res[0]) casadi_copy(w2, 4, res[0]+3);
  /* #26: @0 = zeros(3x1) */
  casadi_clear(w0, 3);
  /* #27: @1 = 1 */
  w1 = 1.;
  /* #28: @5 = @10[2] */
  for (rr=(&w5), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #29: @9 = sq(@5) */
  w9 = casadi_sq( w5 );
  /* #30: @7 = @10[3] */
  for (rr=(&w7), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #31: @16 = sq(@7) */
  w16 = casadi_sq( w7 );
  /* #32: @17 = (@9+@16) */
  w17  = (w9+w16);
  /* #33: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #34: @17 = (@1-@17) */
  w17  = (w1-w17);
  /* #35: @18 = @10[1] */
  for (rr=(&w18), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #36: @19 = (@18*@5) */
  w19  = (w18*w5);
  /* #37: @20 = @10[0] */
  for (rr=(&w20), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #38: @21 = (@20*@7) */
  w21  = (w20*w7);
  /* #39: @22 = (@19-@21) */
  w22  = (w19-w21);
  /* #40: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #41: @23 = (@18*@7) */
  w23  = (w18*w7);
  /* #42: @24 = (@20*@5) */
  w24  = (w20*w5);
  /* #43: @25 = (@23+@24) */
  w25  = (w23+w24);
  /* #44: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #45: @26 = horzcat(@17, @22, @25) */
  rr=w26;
  *rr++ = w17;
  *rr++ = w22;
  *rr++ = w25;
  /* #46: @26 = @26' */
  /* #47: @19 = (@19+@21) */
  w19 += w21;
  /* #48: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #49: @21 = sq(@18) */
  w21 = casadi_sq( w18 );
  /* #50: @16 = (@21+@16) */
  w16  = (w21+w16);
  /* #51: @16 = (2.*@16) */
  w16 = (2.* w16 );
  /* #52: @16 = (@1-@16) */
  w16  = (w1-w16);
  /* #53: @5 = (@5*@7) */
  w5 *= w7;
  /* #54: @20 = (@20*@18) */
  w20 *= w18;
  /* #55: @18 = (@5-@20) */
  w18  = (w5-w20);
  /* #56: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #57: @27 = horzcat(@19, @16, @18) */
  rr=w27;
  *rr++ = w19;
  *rr++ = w16;
  *rr++ = w18;
  /* #58: @27 = @27' */
  /* #59: @23 = (@23-@24) */
  w23 -= w24;
  /* #60: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #61: @5 = (@5+@20) */
  w5 += w20;
  /* #62: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #63: @21 = (@21+@9) */
  w21 += w9;
  /* #64: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #65: @1 = (@1-@21) */
  w1 -= w21;
  /* #66: @28 = horzcat(@23, @5, @1) */
  rr=w28;
  *rr++ = w23;
  *rr++ = w5;
  *rr++ = w1;
  /* #67: @28 = @28' */
  /* #68: @29 = horzcat(@26, @27, @28) */
  rr=w29;
  for (i=0, cs=w26; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<3; ++i) *rr++ = *cs++;
  /* #69: @30 = @29' */
  for (i=0, rr=w30, cs=w29; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #70: @23 = 8.54858 */
  w23 = 8.5485799999999994e+00;
  /* #71: @5 = input[1][0] */
  w5 = arg[1] ? arg[1][0] : 0;
  /* #72: @1 = input[1][1] */
  w1 = arg[1] ? arg[1][1] : 0;
  /* #73: @21 = input[1][2] */
  w21 = arg[1] ? arg[1][2] : 0;
  /* #74: @9 = input[1][3] */
  w9 = arg[1] ? arg[1][3] : 0;
  /* #75: @10 = vertcat(@5, @1, @21, @9) */
  rr=w10;
  *rr++ = w5;
  *rr++ = w1;
  *rr++ = w21;
  *rr++ = w9;
  /* #76: @10 = (@23*@10) */
  for (i=0, rr=w10, cs=w10; i<4; ++i) (*rr++)  = (w23*(*cs++));
  /* #77: @23 = @10[0] */
  for (rr=(&w23), ss=w10+0; ss!=w10+1; ss+=1) *rr++ = *ss;
  /* #78: @5 = @10[1] */
  for (rr=(&w5), ss=w10+1; ss!=w10+2; ss+=1) *rr++ = *ss;
  /* #79: @23 = (@23+@5) */
  w23 += w5;
  /* #80: @5 = @10[2] */
  for (rr=(&w5), ss=w10+2; ss!=w10+3; ss+=1) *rr++ = *ss;
  /* #81: @23 = (@23+@5) */
  w23 += w5;
  /* #82: @5 = @10[3] */
  for (rr=(&w5), ss=w10+3; ss!=w10+4; ss+=1) *rr++ = *ss;
  /* #83: @23 = (@23+@5) */
  w23 += w5;
  /* #84: @26 = vertcat(@3, @3, @23) */
  rr=w26;
  *rr++ = w3;
  *rr++ = w3;
  *rr++ = w23;
  /* #85: @23 = 2.064 */
  w23 = 2.0640000000000001e+00;
  /* #86: @26 = (@26/@23) */
  for (i=0, rr=w26; i<3; ++i) (*rr++) /= w23;
  /* #87: @0 = mac(@30,@26,@0) */
  for (i=0, rr=w0; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w30+j, tt=w26+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #88: @26 = [0, 0, 9.81] */
  casadi_copy(casadi_c0, 3, w26);
  /* #89: @0 = (@0-@26) */
  for (i=0, rr=w0, cs=w26; i<3; ++i) (*rr++) -= (*cs++);
  /* #90: output[0][2] = @0 */
  if (res[0]) casadi_copy(w0, 3, res[0]+7);
  /* #91: @10 = @10' */
  /* #92: @2 = [-0.173948, -0.173948, 0.173948, 0.173948] */
  casadi_copy(casadi_c1, 4, w2);
  /* #93: @23 = mac(@10,@2,@3) */
  casadi_copy((&w3), 1, (&w23));
  for (i=0, rr=(&w23); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w10+j, tt=w2+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #94: @5 = -0.0184715 */
  w5 = -1.8471453789999998e-02;
  /* #95: @5 = (@5*@6) */
  w5 *= w6;
  /* #96: @5 = (@5*@8) */
  w5 *= w8;
  /* #97: @23 = (@23+@5) */
  w23 += w5;
  /* #98: @5 = 0.0236152 */
  w5 = 2.3615184960000001e-02;
  /* #99: @23 = (@23/@5) */
  w23 /= w5;
  /* #100: output[0][3] = @23 */
  if (res[0]) res[0][10] = w23;
  /* #101: @23 = 0.0185744 */
  w23 = 1.8574378599999997e-02;
  /* #102: @23 = (@23*@8) */
  w23 *= w8;
  /* #103: @23 = (@23*@4) */
  w23 *= w4;
  /* #104: @2 = [0.173948, -0.173948, -0.173948, 0.173948] */
  casadi_copy(casadi_c2, 4, w2);
  /* #105: @8 = mac(@10,@2,@3) */
  casadi_copy((&w3), 1, (&w8));
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w10+j, tt=w2+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #106: @23 = (@23-@8) */
  w23 -= w8;
  /* #107: @8 = 0.0237181 */
  w8 = 2.3718109769999999e-02;
  /* #108: @23 = (@23/@8) */
  w23 /= w8;
  /* #109: output[0][4] = @23 */
  if (res[0]) res[0][11] = w23;
  /* #110: @2 = [-0.016, 0.016, -0.016, 0.016] */
  casadi_copy(casadi_c3, 4, w2);
  /* #111: @3 = mac(@10,@2,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w10+j, tt=w2+i*4; k<4; ++k) *rr += ss[k*1]**tt++;
  /* #112: @23 = -0.000102925 */
  w23 = -1.0292480999999840e-04;
  /* #113: @23 = (@23*@4) */
  w23 *= w4;
  /* #114: @23 = (@23*@6) */
  w23 *= w6;
  /* #115: @3 = (@3+@23) */
  w3 += w23;
  /* #116: @23 = 0.0421896 */
  w23 = 4.2189563559999997e-02;
  /* #117: @3 = (@3/@23) */
  w3 /= w23;
  /* #118: output[0][5] = @3 */
  if (res[0]) res[0][12] = w3;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void quad_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int quad_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real quad_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quad_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quad_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 104;
  return 0;
}

CASADI_SYMBOL_EXPORT int quad_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 104*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
