/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) broken_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[21] = {17, 1, 0, 17, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};
static const casadi_int casadi_s3[18] = {17, 1, 0, 14, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16};

static const casadi_real casadi_c0[4] = {1.6000000000000000e-02, 1.6000000000000000e-02, -1.6000000000000000e-02, -1.6000000000000000e-02};
static const casadi_real casadi_c1[4] = {1.7399999999999999e-01, -1.7399999999999999e-01, 1.7399999999999999e-01, -1.7399999999999999e-01};
static const casadi_real casadi_c2[4] = {-1.7399999999999999e-01, 1.7399999999999999e-01, 1.7399999999999999e-01, -1.7399999999999999e-01};

/* broken_expl_vde_adj:(i0[13],i1[13],i2[4],i3[17])->(o0[17x1,14nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *ss, *tt;
  const casadi_real *cs;
  casadi_real *w0=w+4, *w1=w+8, w2, *w3=w+13, *w4=w+22, *w5=w+35, *w6=w+38, *w7=w+42, w8, w9, w10, w11, w12, w13, w14, w15, w16, *w17=w+54, *w18=w+58, *w19=w+61, *w20=w+70, *w21=w+73, w22, w23, w24, w25, w26, w27, w28, w29, w30, w31, w32, *w33=w+87, *w34=w+91, *w35=w+95, *w36=w+99, *w37=w+103, *w38=w+119;
  /* #0: @0 = zeros(4x1) */
  casadi_clear(w0, 4);
  /* #1: @1 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 4, w1);
  /* #2: @2 = @1[1] */
  for (rr=(&w2), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #3: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #4: @4 = input[1][0] */
  casadi_copy(arg[1], 13, w4);
  /* #5: {@5, @6, @7, @8, @9, @10} = vertsplit(@4) */
  casadi_copy(w4, 3, w5);
  casadi_copy(w4+3, 4, w6);
  casadi_copy(w4+7, 3, w7);
  w8 = w4[10];
  w9 = w4[11];
  w10 = w4[12];
  /* #6: @11 = 0 */
  w11 = 0.;
  /* #7: @12 = 17 */
  w12 = 17.;
  /* #8: @13 = input[2][0] */
  w13 = arg[2] ? arg[2][0] : 0;
  /* #9: @14 = input[2][1] */
  w14 = arg[2] ? arg[2][1] : 0;
  /* #10: @15 = input[2][2] */
  w15 = arg[2] ? arg[2][2] : 0;
  /* #11: @16 = input[2][3] */
  w16 = arg[2] ? arg[2][3] : 0;
  /* #12: @17 = vertcat(@13, @14, @15, @16) */
  rr=w17;
  *rr++ = w13;
  *rr++ = w14;
  *rr++ = w15;
  *rr++ = w16;
  /* #13: @17 = (@12*@17) */
  for (i=0, rr=w17, cs=w17; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #14: @13 = @17[0] */
  for (rr=(&w13), ss=w17+0; ss!=w17+1; ss+=1) *rr++ = *ss;
  /* #15: @13 = (-@13) */
  w13 = (- w13 );
  /* #16: @14 = @17[1] */
  for (rr=(&w14), ss=w17+1; ss!=w17+2; ss+=1) *rr++ = *ss;
  /* #17: @13 = (@13-@14) */
  w13 -= w14;
  /* #18: @14 = @17[2] */
  for (rr=(&w14), ss=w17+2; ss!=w17+3; ss+=1) *rr++ = *ss;
  /* #19: @13 = (@13-@14) */
  w13 -= w14;
  /* #20: @14 = @17[3] */
  for (rr=(&w14), ss=w17+3; ss!=w17+4; ss+=1) *rr++ = *ss;
  /* #21: @13 = (@13-@14) */
  w13 -= w14;
  /* #22: @18 = vertcat(@11, @11, @13) */
  rr=w18;
  *rr++ = w11;
  *rr++ = w11;
  *rr++ = w13;
  /* #23: @13 = 2.06431 */
  w13 = 2.0643076919999999e+00;
  /* #24: @18 = (@18/@13) */
  for (i=0, rr=w18; i<3; ++i) (*rr++) /= w13;
  /* #25: @18 = @18' */
  /* #26: @3 = mac(@7,@18,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w18+i*1; k<1; ++k) *rr += ss[k*3]**tt++;
  /* #27: @19 = @3' */
  for (i=0, rr=w19, cs=w3; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #28: {@18, @20, @21} = horzsplit(@19) */
  casadi_copy(w19, 3, w18);
  casadi_copy(w19+3, 3, w20);
  casadi_copy(w19+6, 3, w21);
  /* #29: @21 = @21' */
  /* #30: {@13, @14, @15} = horzsplit(@21) */
  w13 = w21[0];
  w14 = w21[1];
  w15 = w21[2];
  /* #31: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #32: @16 = (@2*@14) */
  w16  = (w2*w14);
  /* #33: @22 = @1[2] */
  for (rr=(&w22), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #34: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #35: @23 = (@22*@13) */
  w23  = (w22*w13);
  /* #36: @16 = (@16-@23) */
  w16 -= w23;
  /* #37: @20 = @20' */
  /* #38: {@23, @24, @25} = horzsplit(@20) */
  w23 = w20[0];
  w24 = w20[1];
  w25 = w20[2];
  /* #39: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #40: @26 = (@2*@25) */
  w26  = (w2*w25);
  /* #41: @16 = (@16-@26) */
  w16 -= w26;
  /* #42: @26 = @1[3] */
  for (rr=(&w26), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #43: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #44: @27 = (@26*@23) */
  w27  = (w26*w23);
  /* #45: @16 = (@16+@27) */
  w16 += w27;
  /* #46: @18 = @18' */
  /* #47: {@27, @28, @29} = horzsplit(@18) */
  w27 = w18[0];
  w28 = w18[1];
  w29 = w18[2];
  /* #48: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #49: @30 = (@22*@29) */
  w30  = (w22*w29);
  /* #50: @16 = (@16+@30) */
  w16 += w30;
  /* #51: @28 = (2.*@28) */
  w28 = (2.* w28 );
  /* #52: @30 = (@26*@28) */
  w30  = (w26*w28);
  /* #53: @16 = (@16-@30) */
  w16 -= w30;
  /* #54: @17 = @0; (@17[0] += @16) */
  casadi_copy(w0, 4, w17);
  for (rr=w17+0, ss=(&w16); rr!=w17+1; rr+=1) *rr += *ss++;
  /* #55: @16 = (2.*@2) */
  w16 = (2.* w2 );
  /* #56: @15 = (-@15) */
  w15 = (- w15 );
  /* #57: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #58: @30 = (@16*@15) */
  w30  = (w16*w15);
  /* #59: @31 = @1[0] */
  for (rr=(&w31), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #60: @32 = (@31*@14) */
  w32  = (w31*w14);
  /* #61: @30 = (@30+@32) */
  w30 += w32;
  /* #62: @32 = (@26*@13) */
  w32  = (w26*w13);
  /* #63: @30 = (@30+@32) */
  w30 += w32;
  /* #64: @32 = (@31*@25) */
  w32  = (w31*w25);
  /* #65: @30 = (@30-@32) */
  w30 -= w32;
  /* #66: @24 = (-@24) */
  w24 = (- w24 );
  /* #67: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #68: @16 = (@16*@24) */
  w16 *= w24;
  /* #69: @30 = (@30+@16) */
  w30 += w16;
  /* #70: @16 = (@22*@23) */
  w16  = (w22*w23);
  /* #71: @30 = (@30+@16) */
  w30 += w16;
  /* #72: @16 = (@26*@29) */
  w16  = (w26*w29);
  /* #73: @30 = (@30+@16) */
  w30 += w16;
  /* #74: @16 = (@22*@28) */
  w16  = (w22*w28);
  /* #75: @30 = (@30+@16) */
  w30 += w16;
  /* #76: (@17[1] += @30) */
  for (rr=w17+1, ss=(&w30); rr!=w17+2; rr+=1) *rr += *ss++;
  /* #77: @30 = (@22*@14) */
  w30  = (w22*w14);
  /* #78: @16 = (@2*@13) */
  w16  = (w2*w13);
  /* #79: @30 = (@30+@16) */
  w30 += w16;
  /* #80: @16 = (@22*@25) */
  w16  = (w22*w25);
  /* #81: @30 = (@30+@16) */
  w30 += w16;
  /* #82: @16 = (2.*@26) */
  w16 = (2.* w26 );
  /* #83: @24 = (@16*@24) */
  w24  = (w16*w24);
  /* #84: @30 = (@30+@24) */
  w30 += w24;
  /* #85: @24 = (@31*@23) */
  w24  = (w31*w23);
  /* #86: @30 = (@30+@24) */
  w30 += w24;
  /* #87: @24 = (@2*@29) */
  w24  = (w2*w29);
  /* #88: @30 = (@30+@24) */
  w30 += w24;
  /* #89: @24 = (@31*@28) */
  w24  = (w31*w28);
  /* #90: @30 = (@30-@24) */
  w30 -= w24;
  /* #91: @27 = (-@27) */
  w27 = (- w27 );
  /* #92: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #93: @16 = (@16*@27) */
  w16 *= w27;
  /* #94: @30 = (@30+@16) */
  w30 += w16;
  /* #95: (@17[3] += @30) */
  for (rr=w17+3, ss=(&w30); rr!=w17+4; rr+=1) *rr += *ss++;
  /* #96: @30 = (2.*@22) */
  w30 = (2.* w22 );
  /* #97: @15 = (@30*@15) */
  w15  = (w30*w15);
  /* #98: @14 = (@26*@14) */
  w14  = (w26*w14);
  /* #99: @15 = (@15+@14) */
  w15 += w14;
  /* #100: @13 = (@31*@13) */
  w13  = (w31*w13);
  /* #101: @15 = (@15-@13) */
  w15 -= w13;
  /* #102: @25 = (@26*@25) */
  w25  = (w26*w25);
  /* #103: @15 = (@15+@25) */
  w15 += w25;
  /* #104: @23 = (@2*@23) */
  w23  = (w2*w23);
  /* #105: @15 = (@15+@23) */
  w15 += w23;
  /* #106: @29 = (@31*@29) */
  w29  = (w31*w29);
  /* #107: @15 = (@15+@29) */
  w15 += w29;
  /* #108: @28 = (@2*@28) */
  w28  = (w2*w28);
  /* #109: @15 = (@15+@28) */
  w15 += w28;
  /* #110: @30 = (@30*@27) */
  w30 *= w27;
  /* #111: @15 = (@15+@30) */
  w15 += w30;
  /* #112: (@17[2] += @15) */
  for (rr=w17+2, ss=(&w15); rr!=w17+3; rr+=1) *rr += *ss++;
  /* #113: @18 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w18);
  /* #114: @15 = @18[0] */
  for (rr=(&w15), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #115: @30 = (-@15) */
  w30 = (- w15 );
  /* #116: @27 = @18[1] */
  for (rr=(&w27), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #117: @28 = (-@27) */
  w28 = (- w27 );
  /* #118: @29 = @18[2] */
  for (rr=(&w29), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #119: @23 = (-@29) */
  w23 = (- w29 );
  /* #120: @33 = horzcat(@11, @30, @28, @23) */
  rr=w33;
  *rr++ = w11;
  *rr++ = w30;
  *rr++ = w28;
  *rr++ = w23;
  /* #121: @33 = @33' */
  /* #122: @34 = horzcat(@15, @11, @29, @28) */
  rr=w34;
  *rr++ = w15;
  *rr++ = w11;
  *rr++ = w29;
  *rr++ = w28;
  /* #123: @34 = @34' */
  /* #124: @35 = horzcat(@27, @23, @11, @15) */
  rr=w35;
  *rr++ = w27;
  *rr++ = w23;
  *rr++ = w11;
  *rr++ = w15;
  /* #125: @35 = @35' */
  /* #126: @36 = horzcat(@29, @27, @30, @11) */
  rr=w36;
  *rr++ = w29;
  *rr++ = w27;
  *rr++ = w30;
  *rr++ = w11;
  /* #127: @36 = @36' */
  /* #128: @37 = horzcat(@33, @34, @35, @36) */
  rr=w37;
  for (i=0, cs=w33; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<4; ++i) *rr++ = *cs++;
  /* #129: @30 = 0.5 */
  w30 = 5.0000000000000000e-01;
  /* #130: @6 = (@30*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w30*(*cs++));
  /* #131: @33 = mac(@37,@6,@0) */
  casadi_copy(w0, 4, w33);
  for (i=0, rr=w33; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w37+j, tt=w6+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #132: @17 = (@17+@33) */
  for (i=0, rr=w17, cs=w33; i<4; ++i) (*rr++) += (*cs++);
  /* #133: output[0][0] = @17 */
  casadi_copy(w17, 4, res[0]);
  /* #134: output[0][1] = @5 */
  if (res[0]) casadi_copy(w5, 3, res[0]+4);
  /* #135: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #136: @30 = 0.0358798 */
  w30 = 3.5879797087419341e-02;
  /* #137: @11 = (@30*@29) */
  w11  = (w30*w29);
  /* #138: @23 = 35.7143 */
  w23 = 3.5714285714285715e+01;
  /* #139: @9 = (@23*@9) */
  w9  = (w23*w9);
  /* #140: @11 = (@11*@9) */
  w11 *= w9;
  /* #141: @18 = @5; (@18[0] += @11) */
  casadi_copy(w5, 3, w18);
  for (rr=w18+0, ss=(&w11); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #142: @15 = (@15*@9) */
  w15 *= w9;
  /* #143: @30 = (@30*@15) */
  w30 *= w15;
  /* #144: (@18[2] += @30) */
  for (rr=w18+2, ss=(&w30); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #145: @30 = -0.0358798 */
  w30 = -3.5879797087419341e-02;
  /* #146: @27 = (@30*@27) */
  w27  = (w30*w27);
  /* #147: @23 = (@23*@8) */
  w23 *= w8;
  /* #148: @27 = (@27*@23) */
  w27 *= w23;
  /* #149: (@18[2] += @27) */
  for (rr=w18+2, ss=(&w27); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #150: @29 = (@29*@23) */
  w29 *= w23;
  /* #151: @30 = (@30*@29) */
  w30 *= w29;
  /* #152: (@18[1] += @30) */
  for (rr=w18+1, ss=(&w30); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #153: @37 = zeros(4x4) */
  casadi_clear(w37, 16);
  /* #154: @1 = @1' */
  /* #155: @37 = mac(@6,@1,@37) */
  for (i=0, rr=w37; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w1+i*1; k<1; ++k) *rr += ss[k*4]**tt++;
  /* #156: @38 = @37' */
  for (i=0, rr=w38, cs=w37; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #157: {@6, @1, @17, @33} = horzsplit(@38) */
  casadi_copy(w38, 4, w6);
  casadi_copy(w38+4, 4, w1);
  casadi_copy(w38+8, 4, w17);
  casadi_copy(w38+12, 4, w33);
  /* #158: @33 = @33' */
  /* #159: {@30, @29, @27, NULL} = horzsplit(@33) */
  w30 = w33[0];
  w29 = w33[1];
  w27 = w33[2];
  /* #160: @27 = (-@27) */
  w27 = (- w27 );
  /* #161: (@18[0] += @27) */
  for (rr=w18+0, ss=(&w27); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #162: (@18[1] += @29) */
  for (rr=w18+1, ss=(&w29); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #163: (@18[2] += @30) */
  for (rr=w18+2, ss=(&w30); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #164: @17 = @17' */
  /* #165: {@30, @29, NULL, @27} = horzsplit(@17) */
  w30 = w17[0];
  w29 = w17[1];
  w27 = w17[3];
  /* #166: (@18[0] += @27) */
  for (rr=w18+0, ss=(&w27); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #167: @29 = (-@29) */
  w29 = (- w29 );
  /* #168: (@18[2] += @29) */
  for (rr=w18+2, ss=(&w29); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #169: (@18[1] += @30) */
  for (rr=w18+1, ss=(&w30); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #170: @1 = @1' */
  /* #171: {@30, NULL, @29, @27} = horzsplit(@1) */
  w30 = w1[0];
  w29 = w1[2];
  w27 = w1[3];
  /* #172: @27 = (-@27) */
  w27 = (- w27 );
  /* #173: (@18[1] += @27) */
  for (rr=w18+1, ss=(&w27); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #174: (@18[2] += @29) */
  for (rr=w18+2, ss=(&w29); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #175: (@18[0] += @30) */
  for (rr=w18+0, ss=(&w30); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #176: @6 = @6' */
  /* #177: {NULL, @30, @29, @27} = horzsplit(@6) */
  w30 = w6[1];
  w29 = w6[2];
  w27 = w6[3];
  /* #178: @27 = (-@27) */
  w27 = (- w27 );
  /* #179: (@18[2] += @27) */
  for (rr=w18+2, ss=(&w27); rr!=w18+3; rr+=1) *rr += *ss++;
  /* #180: @29 = (-@29) */
  w29 = (- w29 );
  /* #181: (@18[1] += @29) */
  for (rr=w18+1, ss=(&w29); rr!=w18+2; rr+=1) *rr += *ss++;
  /* #182: @30 = (-@30) */
  w30 = (- w30 );
  /* #183: (@18[0] += @30) */
  for (rr=w18+0, ss=(&w30); rr!=w18+1; rr+=1) *rr += *ss++;
  /* #184: output[0][2] = @18 */
  if (res[0]) casadi_copy(w18, 3, res[0]+7);
  /* #185: @30 = 15.6544 */
  w30 = 1.5654401635488957e+01;
  /* #186: @30 = (@30*@10) */
  w30 *= w10;
  /* #187: @6 = [0.016, 0.016, -0.016, -0.016] */
  casadi_copy(casadi_c0, 4, w6);
  /* #188: @6 = @6' */
  /* #189: @6 = (@30*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w30*(*cs++));
  /* #190: @6 = @6' */
  /* #191: @1 = [0.174, -0.174, 0.174, -0.174] */
  casadi_copy(casadi_c1, 4, w1);
  /* #192: @1 = @1' */
  /* #193: @1 = (@9*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w9*(*cs++));
  /* #194: @1 = @1' */
  /* #195: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #196: @1 = [-0.174, 0.174, 0.174, -0.174] */
  casadi_copy(casadi_c2, 4, w1);
  /* #197: @1 = @1' */
  /* #198: @1 = (@23*@1) */
  for (i=0, rr=w1, cs=w1; i<4; ++i) (*rr++)  = (w23*(*cs++));
  /* #199: @1 = @1' */
  /* #200: @6 = (@6+@1) */
  for (i=0, rr=w6, cs=w1; i<4; ++i) (*rr++) += (*cs++);
  /* #201: @6 = (@12*@6) */
  for (i=0, rr=w6, cs=w6; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #202: @23 = 0.484424 */
  w23 = 4.8442390825524284e-01;
  /* #203: @9 = 1 */
  w9 = 1.;
  /* #204: @30 = sq(@22) */
  w30 = casadi_sq( w22 );
  /* #205: @10 = sq(@26) */
  w10 = casadi_sq( w26 );
  /* #206: @29 = (@30+@10) */
  w29  = (w30+w10);
  /* #207: @29 = (2.*@29) */
  w29 = (2.* w29 );
  /* #208: @29 = (@9-@29) */
  w29  = (w9-w29);
  /* #209: @27 = (@2*@22) */
  w27  = (w2*w22);
  /* #210: @8 = (@31*@26) */
  w8  = (w31*w26);
  /* #211: @15 = (@27-@8) */
  w15  = (w27-w8);
  /* #212: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #213: @11 = (@2*@26) */
  w11  = (w2*w26);
  /* #214: @28 = (@31*@22) */
  w28  = (w31*w22);
  /* #215: @25 = (@11+@28) */
  w25  = (w11+w28);
  /* #216: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #217: @18 = horzcat(@29, @15, @25) */
  rr=w18;
  *rr++ = w29;
  *rr++ = w15;
  *rr++ = w25;
  /* #218: @18 = @18' */
  /* #219: @27 = (@27+@8) */
  w27 += w8;
  /* #220: @27 = (2.*@27) */
  w27 = (2.* w27 );
  /* #221: @8 = sq(@2) */
  w8 = casadi_sq( w2 );
  /* #222: @10 = (@8+@10) */
  w10  = (w8+w10);
  /* #223: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #224: @10 = (@9-@10) */
  w10  = (w9-w10);
  /* #225: @22 = (@22*@26) */
  w22 *= w26;
  /* #226: @31 = (@31*@2) */
  w31 *= w2;
  /* #227: @2 = (@22-@31) */
  w2  = (w22-w31);
  /* #228: @2 = (2.*@2) */
  w2 = (2.* w2 );
  /* #229: @20 = horzcat(@27, @10, @2) */
  rr=w20;
  *rr++ = w27;
  *rr++ = w10;
  *rr++ = w2;
  /* #230: @20 = @20' */
  /* #231: @11 = (@11-@28) */
  w11 -= w28;
  /* #232: @11 = (2.*@11) */
  w11 = (2.* w11 );
  /* #233: @22 = (@22+@31) */
  w22 += w31;
  /* #234: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #235: @8 = (@8+@30) */
  w8 += w30;
  /* #236: @8 = (2.*@8) */
  w8 = (2.* w8 );
  /* #237: @9 = (@9-@8) */
  w9 -= w8;
  /* #238: @21 = horzcat(@11, @22, @9) */
  rr=w21;
  *rr++ = w11;
  *rr++ = w22;
  *rr++ = w9;
  /* #239: @21 = @21' */
  /* #240: @19 = horzcat(@18, @20, @21) */
  rr=w19;
  for (i=0, cs=w18; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<3; ++i) *rr++ = *cs++;
  /* #241: @5 = mac(@19,@7,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w19+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #242: @5 = (@23*@5) */
  for (i=0, rr=w5, cs=w5; i<3; ++i) (*rr++)  = (w23*(*cs++));
  /* #243: {NULL, NULL, @23} = vertsplit(@5) */
  w23 = w5[2];
  /* #244: @23 = (-@23) */
  w23 = (- w23 );
  /* #245: (@0[3] += @23) */
  for (rr=w0+3, ss=(&w23); rr!=w0+4; rr+=1) *rr += *ss++;
  /* #246: (@0[2] += @23) */
  for (rr=w0+2, ss=(&w23); rr!=w0+3; rr+=1) *rr += *ss++;
  /* #247: (@0[1] += @23) */
  for (rr=w0+1, ss=(&w23); rr!=w0+2; rr+=1) *rr += *ss++;
  /* #248: (@0[0] += @23) */
  for (rr=w0+0, ss=(&w23); rr!=w0+1; rr+=1) *rr += *ss++;
  /* #249: @0 = (@12*@0) */
  for (i=0, rr=w0, cs=w0; i<4; ++i) (*rr++)  = (w12*(*cs++));
  /* #250: @6 = (@6+@0) */
  for (i=0, rr=w6, cs=w0; i<4; ++i) (*rr++) += (*cs++);
  /* #251: {@12, @23, @11, @22} = vertsplit(@6) */
  w12 = w6[0];
  w23 = w6[1];
  w11 = w6[2];
  w22 = w6[3];
  /* #252: output[0][3] = @12 */
  if (res[0]) res[0][10] = w12;
  /* #253: output[0][4] = @23 */
  if (res[0]) res[0][11] = w23;
  /* #254: output[0][5] = @11 */
  if (res[0]) res[0][12] = w11;
  /* #255: output[0][6] = @22 */
  if (res[0]) res[0][13] = w22;
  return 0;
}

CASADI_SYMBOL_EXPORT int broken_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int broken_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int broken_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void broken_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int broken_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void broken_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void broken_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void broken_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int broken_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int broken_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real broken_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* broken_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* broken_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* broken_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* broken_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int broken_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 135;
  return 0;
}

CASADI_SYMBOL_EXPORT int broken_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 135*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
